# Compiler
CC = gcc

# Compiler flags
CFLAGS = -Wall -g -MMD -MP

# Find all .c files
SRC := $(shell find . -name "*.c")

# Object files
OBJ := $(SRC:.c=.o)

# Dependency files (.d files generated by gcc)
DEP := $(OBJ:.o=.d)

# Executable
TARGET = Exel_Program

# Default target
all: $(TARGET)

# Link
$(TARGET): $(OBJ)
	$(CC) $(CFLAGS) -o $@ $^

# Compile
%.o: %.c
	$(CC) $(CFLAGS) -c $< -o $@

# Include dependency files
-include $(DEP)

# Clean
clean:
	rm -f $(OBJ) $(DEP) $(TARGET)
